"""
Pydantic models representing the state and decisions of the Supervisor Agent.
These models are used across the orchestration layer.
"""

from enum import Enum
from typing import List, Optional, Dict, Any
from uuid import UUID
from pydantic import BaseModel, Field


class AgentType(str, Enum):
    """Enumeration of available agent types in the OmniBrain system."""

    SEARCH = "SEARCH"
    VISION = "VISION"
    SUMMARY = "SUMMARY"
    SQL = "SQL"
    UNKNOWN = "UNKNOWN"


class RoutingDecision(BaseModel):
    """
    The result of the routing process.
    Contains the list of agents to invoke, a confidence score, and a reasoning string.
    """

    selected_agents: List[AgentType] = Field(
        ...,
        description="Ordered list of agents that should handle the request.",
    )
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence score of the routing decision."
    )
    reason: str = Field(..., description="Human‑readable justification for the routing.")


class AgentState(BaseModel):
    """
    Complete state object maintained for each user interaction.
    This state is passed through the agent pipeline.
    """

    conversation_id: UUID = Field(..., description="Unique identifier for the conversation.")
    document_id: Optional[UUID] = Field(
        None, description="Target document ID, if provided."
    )
    user_query: str = Field(..., description="Original query from the user.")
    selected_agents: List[AgentType] = Field(
        default_factory=list,
        description="Agents selected by the Supervisor for this request.",
    )
    retrieved_chunks: List[str] = Field(
        default_factory=list,
        description="Text chunks retrieved by the Search Agent (populated later).",
    )
    retrieved_images: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Image data retrieved by the Vision Agent (populated later).",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata (e.g., page numbers, timestamps).",
    )
    final_answer: Optional[str] = Field(
        None, description="Final answer generated by the system (populated later)."
    )
    processing_time: Optional[float] = Field(
        None, description="Total processing time in seconds (populated later)."
    )